site_name: Docs site
site_url: https://ivancheban.github.io/my-project/
nav:
    - Introduction: 'index.md'
    - User Guide:
        - 'Test': 'test-folder/test.md'
        - 'Test 1': 'test-folder/test1.md'
        - 'Test 2': 'test-folder/test2.md'
    - About:
        - 'About this site': 'about.md'
theme:
  features:
    - navigation.footer
  name: material
  logo: img/logo.svg
  favicon: img/favicon.ico
  palette: 
    scheme: default
    accent: light blue
  
extra_css:
  - stylesheets/extra.css

extra:
  generator: false

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true



